### ISSUE TITLE
Traditional Chinese Translation Progress

### ISSUE THREAD

**Issue by gatsbybot** [gatsbyjs/gatsby-zh-Hant#1]
## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, please read the [translation guide](https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/#contributing-to-a-translation) to understand the Gatsby translation process.

Please be prompt with your translations! If you find that you can't commit anymore, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

- [ ] Home Page (@gatsbybot) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

**These pages should be translated first.** These pages must be translated to be considered an official Gatsby localization.

### Community

* [ ] community/code-of-conduct (@dsewnr)
    

### Tutorial

* [ ] tutorial/index(@yunkii) - #5 
* [ ] tutorial/part-zero
* [ ] tutorial/part-one
* [ ] tutorial/part-two
* [ ] tutorial/part-three
* [ ] tutorial/part-four
* [ ] tutorial/part-five
* [ ] tutorial/part-six
* [ ] tutorial/part-seven
* [ ] tutorial/part-eight
    

### Docs

* [ ] docs/index
* [ ] docs/quick-start(@yunkii) - #5 
* [ ] docs/glossary
* [ ] docs/gatsby-cli

#### Recipes

* [ ] docs/recipes
* [ ] docs/recipes/pages-layouts
* [ ] docs/recipes/styling-css
* [ ] docs/recipes/working-with-starters
* [ ] docs/recipes/working-with-themes
* [ ] docs/recipes/sourcing-data
* [ ] docs/recipes/querying-data
* [ ] docs/recipes/working-with-images
* [ ] docs/recipes/transforming-data
* [ ] docs/recipes/deploying-your-site

#### API Reference

* [ ] docs/api-reference
* [ ] docs/theme-api
* [ ] docs/gatsby-link
* [ ] docs/gatsby-image
* [ ] docs/gatsby-config
* [ ] docs/browser-apis
* [ ] docs/ssr-apis
* [ ] docs/api-files
* [ ] docs/api-files-gatsby-config
* [ ] docs/api-files-gatsby-browser
* [ ] docs/api-files-gatsby-node
* [ ] docs/api-files-gatsby-ssr
* [ ] docs/actions
* [ ] docs/graphql-api
* [ ] docs/node-apis
* [ ] docs/node-api-helpers
* [ ] docs/node-model
* [ ] docs/node-interface
* [ ] docs/schema-customization
* [ ] docs/api-specification

**Comment by dsewnr** [comment]
`community/code-of-conduct` 應該指的是 `contributing/code-of-conduct`

> ### Community
> * [ ]  community/code-of-conduct

**Comment by coleenhuang** [comment]
I'd like to try and translate tutorial/part four
